University/Models/Group.cs
namespace University.Models
{
    public class Group
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public Guid? CourseId { get; set; }
        public Course? Course { get; set; }
        public Guid? CuratorId { get; set; }
        public Teacher? Curator { get; set; }
        public ICollection<Student> Students { get; set; }
    }
}

University/Models/GroupsViewModel.cs
namespace University.Models
{
    public class GroupsViewModel
    {
        public List<Group> Groups { get; set; } = new List<Group>();
        public List<Course>? UniqueCourses { get; set; }
        public Course? SelectedCourse { get; set; }
        public string SearchTerm { get; set; } = string.Empty;
        public List<Group> FilteredGroups { get; set; } = new List<Group>();
        public List<Teacher> Teachers { get; set; } = new List<Teacher>();
    }
}

University/ViewModels/GroupsViewModel.cs
using University.Models;

namespace University.ViewModels
{
    public class GroupsViewModel
    {
        public List<Group> Groups { get; set; } = new List<Group>();
        public List<Course>? UniqueCourses { get; set; }
        public Course? SelectedCourse { get; set; }
        public string SearchTerm { get; set; } = string.Empty;
        public List<Group> FilteredGroups { get; set; } = new List<Group>();
        public List<Teacher> Teachers { get; set; } = new List<Teacher>();
    }
}

University/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using University.Models;
using University.ViewModels;

namespace University.Controllers
{
    public class CourseController : Controller
    {
        private readonly ILogger<CourseController> _logger;

        ApplicationContext db;

        public CourseController(ILogger<CourseController> logger, ApplicationContext context)
        {
            _logger = logger;
            db = context;
        }

        public async Task<IActionResult> Courses(string? searchCourse)
        {
            var courses = await db.Courses.ToListAsync();
            List<Course> filteredCourses = courses;

            if (!string.IsNullOrEmpty(searchCourse))
            {
                var searchCourseCopy = searchCourse.ToLower();
                filteredCourses = filteredCourses.Where(g => g.Name.ToLower().Contains(searchCourseCopy)).ToList();
            }

            var model = new CoursesViewModel
            {
                Courses = courses,
                SearchCourse = searchCourse,
                FilteredCourses = filteredCourses
            };

            ViewData["Title"] = "Courses List";
            return View("Courses", model);
        }
        [HttpGet]
        public async Task<IActionResult> SearchCourses(string? searchCourse)
        {
            return RedirectToAction("Courses", new { searchCourse });
        }
        [HttpPost]
        public async Task<IActionResult> CreateCourse(string? createName, string? createDesc)
        {
            Course newCourse = new Course
            {
                Name = createName,
                Description = createDesc
            };
            await db.Courses.AddAsync(newCourse);
            await db.SaveChangesAsync();
            return RedirectToAction("Courses");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateCourse(Guid updateId, string? updateName, string? updateDesc)
        {
            var course = await db.Courses.FirstOrDefaultAsync(c => c.Id == updateId);
            if (course != null)
            {
                course.Name = updateName;
                course.Description = updateDesc;
                db.Courses.Update(course);
                await db.SaveChangesAsync();
            }
            
            return RedirectToAction("Courses");
        }
        public async Task<IActionResult> DeleteCourse(Guid CourseID)
        {
            var course = await db.Courses.FindAsync(CourseID);
            if (course != null)
            {
                db.Courses.Remove(course);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Courses");
        }


        [HttpGet]
        public async Task<IActionResult> VerifyCourseName(string createName)
        {
            var isUnique = !await db.Courses.AnyAsync(t => t.Name == createName);
            return Json(isUnique);
        }
    }
}

University/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using University.Models;
using University.ViewModels;

namespace University.Controllers
{
    public class GroupController : Controller
    {
        private readonly ILogger<GroupController> _logger;

        ApplicationContext db;

        public GroupController(ILogger<GroupController> logger, ApplicationContext context)
        {
            _logger = logger;
            db = context;
        }

        public async Task<IActionResult> Groups(Guid? selectedCourse, string searchTerm)
        {
            var groups = await db.Groups.Include(g => g.Course).Include(g => g.Curator).ToListAsync();
            var courses = await db.Courses.ToListAsync();

            var uniqueNames = new HashSet<string>();
            var uniqueCourses = new List<Course>();

            foreach (var course in courses)
            {
                if (uniqueNames.Add(course.Name))
                {
                    uniqueCourses.Add(course);
                }
            }

            List<Group> filteredGroups = groups;
            Course selectedcourse = new Course();

            if (selectedCourse != null && selectedCourse != Guid.Empty)
            {
                filteredGroups = filteredGroups.Where(g => g.Course.Id == selectedCourse).ToList();
                selectedcourse = await db.Courses.FirstOrDefaultAsync(g => g.Id == selectedCourse);
            }

            if (!string.IsNullOrEmpty(searchTerm))
            {
                var searchTermcopy = searchTerm.ToLower();
                filteredGroups = filteredGroups.Where(g => g.Name.ToLower().Contains(searchTermcopy)).ToList();
            }

            var model = new GroupsViewModel
            {
                Groups = groups,
                UniqueCourses = uniqueCourses,
                SelectedCourse = selectedcourse,
                SearchTerm = searchTerm,
                FilteredGroups = filteredGroups,
                Teachers = await db.Teachers.ToListAsync()
            };

            ViewData["Title"] = "Groups List";
            return View("Groups", model);
        }
        [HttpGet]
        public async Task<IActionResult> SearchGroups(Guid? selectedCourse, string searchTerm)
        {
            return RedirectToAction("Groups", new { selectedCourse, searchTerm });
        }
        [HttpPost]
        public async Task<IActionResult> CreateGroup(string? createName, Guid createCourse, Guid createCurator, string createDesc = "")
        {
            Group newGroup = new Group
            {
                Name = createName,
                Description = createDesc,
                CourseId = (createCourse != null && createCourse != Guid.Empty ? createCourse : null),
                Course = (createCourse != null && createCourse != Guid.Empty ? await db.Courses.FindAsync(createCourse) : null),
                CuratorId = (createCurator != null && createCurator != Guid.Empty) ? createCurator : null,
                Curator = (createCurator != null && createCurator != Guid.Empty) ? await db.Teachers.FindAsync(createCurator) : null
            };
            await db.Groups.AddAsync(newGroup);
            await db.SaveChangesAsync();
            return RedirectToAction("Groups");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateGroup(Guid updateId, string? updateName, Guid updateCourse, Guid updateCurator, string updateDesc = "")
        {
            var group = await db.Groups.Include(g => g.Course).Include(g => g.Curator).FirstOrDefaultAsync(t => t.Id == updateId);
            if (group != null)
            {
                group.Name = updateName;
                group.Description = updateDesc;
                group.CourseId = (updateCourse != null && updateCourse != Guid.Empty) ? updateCourse : null;
                group.Course = (updateCourse != null && updateCourse != Guid.Empty ? await db.Courses.FindAsync(updateCourse) : null);

                if (updateCurator != null && updateCurator != Guid.Empty)
                {
                    group.CuratorId = updateCurator;
                    group.Curator = await db.Teachers.FindAsync(updateCurator);
                }
                db.Update(group);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Groups");
        }
        public async Task<IActionResult> DeleteGroup(Guid GroupID)
        {
            var group = await db.Groups.FindAsync(GroupID);
            if (group != null)
            {
                db.Groups.Remove(group);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Groups");
        }

        [HttpGet]
        public async Task<IActionResult> VerifyGroupNameAsync(string createName)
        {
            var isUnique = !await db.Groups.AnyAsync(t => t.Name == createName);
            return Json(isUnique);
        }
    }
}

University/Views/Group/Groups.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model University.ViewModels.GroupsViewModel

@{
    var user = await UserManager.GetUserAsync(User);
    var isAdmin = user != null ? await UserManager.IsInRoleAsync(user, "Admin") : false;
}

<form class="filter__form" asp-action="SearchGroups" asp-controller="Group" method="get">
    <div>
        <label>Название: </label>
        <input type="text" name="searchTerm" placeholder="Название группы..." value="@Model.SearchTerm" />

        <label>Курс: </label>
        <select name="selectedCourse">
            <option value="">Все курсы</option>
            @foreach (var course in Model.UniqueCourses)
            {
                <option value="@course.Id" selected="@(Model.SelectedCourse == course)">@course.Name</option>
            }
        </select>
        <input type="submit" value="Поиск" />
    </div>
</form>

<table>
    <caption>Группы</caption>
    <thead>
        <td>Наименование</td>
        <td>Описание</td>
        <td>Курс</td>
        <td>Куратор</td>
        <td>Студенты</td>
        @if (isAdmin)
        {
            <td colspan="2">Действия</td>
        }
    </thead>
    @if (Model.FilteredGroups != null && Model.FilteredGroups.Any())
    {
        @foreach (var group in Model.FilteredGroups)
        {
            <tr>
                <td>@group.Name</td>
                <td class="table__col_description">@(!string.IsNullOrEmpty(@group.Description) ? @group.Description : "*Пусто*")</td>
                <td><a asp-controller="Course" asp-action="SearchCourses" asp-route-searchCourse="@(@group.Course != null ? @group.Course.Name : "")">@(@group.Course != null ? @group.Course.Name : "Пусто")</a></td>
                <td>
                    @if (group.Curator == null)
                    {
                        <p>Пусто</p>
                    }
                    else
                    {
                        <a target="_blank" asp-controller="Teacher" asp-action="SearchTeachers" asp-route-selectedTeacher="@group.Curator.Name">@(@group.Curator.Surname + " " + @group.Curator.Name[0] + ". " + @group.Curator.Patronymic[0] + ". ")</a>
                    }
                </td>
                <td><a asp-controller="Student" asp-action="SearchStudents" asp-route-searchGroup="@group.Name">Просмотреть</a></td>
                @if (isAdmin)
                {
                    <td>
                        <button type="button" class="update__button"
                                data-id="@group.Id"
                                data-name="@group.Name"
                                data-description="@group.Description"
                                data-course="@group.CourseId"
                                data-curator="@group.CuratorId">
                            Изменить
                        </button>
                    </td>
                    <td><a asp-action="DeleteGroup" asp-controller="Group" asp-route-GroupID="@group.Id">Удалить</a></td>
                }
            </tr>
        }
    }
    else
    {
        <tfoot><td  colspan="@(isAdmin ?7:5)">Результатов нет</td></tfoot>
    }
</table>

@if (isAdmin)
{
    <div class="add__button_container">
        <button type="button" id="add__button" class="add__button">+Добавить</button>
    </div>

    <div class="create__container" style="display: none;">
        <form class="create__form" asp-action="CreateGroup" asp-controller="Group" method="post">
            <p class="create__name">Наименование группы: </p>
            <input name="createName" placeholder="Наименование..." required>
            <p class="create__description">Описание:</p>
            <input name="createDesc" placeholder="Описание...">
            <p class="create__course">Курс:</p>
            @if (Model.UniqueCourses.Count != 0)
            {
                <select name="createCourse" id="" required>
                    @foreach (var course in Model.UniqueCourses)
                    {
                        <option value="@course.Id">@course.Name</option>
                    }
                </select>
            }
            else
            {
                <button type="button" class="create__course" onclick="location.href='@Url.Action("Courses", "Course")'">Создать курс</button>
            }
            <p class="create__teacher">Куратор (свободный): </p>
            @{
                List<Teacher> freeTeachers = Model.Teachers.Where(t => t.Group == null).ToList();
            }
            @if (@freeTeachers.Count != 0)
            {
                <select name="createCurator" id="" required>
                    @foreach (var teacher in Model.Teachers.Where(t => t.Group == null))
                    {
                        <option value="@teacher.Id">@(@teacher.Surname + " " + teacher.Name + " " + teacher.Patronymic)</option>
                    }
                </select>
                <input class="create__btn" type="submit" value="Создать группу">
            }
            else
            {
                <button type="button" class="create__teacher" onclick="location.href='@Url.Action("Teachers", "Teacher")'">Добавить преподавателя</button>
            }
        </form>
    </div>

    <div class="update__container" style="display: none;">
        <form class="update__form" asp-action="UpdateGroup" asp-controller="Group" method="post">
            <input type="hidden" name="originalName" value="" id="originalName">
            <input type="hidden" name="updateId" id="updateGroupId" />
            <p class="update__name">Наименование группы: </p>
            <input name="updateName" placeholder="Наименование..." required>
            <p class="update__description">Описание:</p>
            <input name="updateDesc" placeholder="Описание...">
            <p class="update__course">Курс:</p>
            @if (Model.UniqueCourses.Count != 0)
            {
                <select name="updateCourse" id="" required>
                    @foreach (var course in Model.UniqueCourses)
                    {
                        <option value="@course.Id">@course.Name</option>
                    }
                </select>
            }
            else
            {
                <button type="button" class="create__course" onclick="location.href='@Url.Action("Courses", "Course")'">Создать курс</button>
            }
            <p class="update__teacher">Куратор (свободный): </p>
            @{
                List<Teacher> freTeachers = Model.Teachers.Where(t => t.Group == null).ToList();
            }
            @if (@freTeachers.Count != 0)
            {
                <select name="updateCurator" id="updateCurator">
                    <option selected>Оставить текущего</option>
                    @foreach (var teacher in Model.Teachers.Where(t => t.Group == null))
                    {
                        <option value="@teacher.Id">@(@teacher.Surname + " " + teacher.Name + " " + teacher.Patronymic)</option>
                    }
                </select>
                <input class="update__btn" type="submit" value="Обновить информацию">
            }
            else
            {
                <button type="button" class="create__teacher" onclick="location.href='@Url.Action("Teachers", "Teacher")'">Добавить преподавателя</button>
                <input class="update__btn" type="submit" value="Обновить информацию">
            }
        </form>
    </div>
}

@section Scripts{
    <script>
        $(document).ready(function () {
            $('.update__button').on('click', function () {
                var groupId = $(this).data('id');
                var groupName = $(this).data('name');
                var groupDescription = $(this).data('description');
                var groupCourse = $(this).data('course');
                var groupCurator = $(this).data('curator');

                $('#updateGroupId').val(groupId);
                $('input[name="updateName"]').val(groupName);
                $('input[name="updateDesc"]').val(groupDescription);
                $('#originalName').val(groupName);

                $('select[name="updateCourse"]').val(groupCourse);
                // $('select[name="updateCurator"]').val(groupCurator);


                $('#add__button').text('Закрыть');
                if (!$('.update__container').is(':visible')) {
                    $('.create__container').hide();
                    $('.update__container').show();
                }
            });
            $('#add__button').on('click', function () {
                if (!$('.create__container').is(':visible') && !$('.update__container').is(':visible')) {
                    $('.create__container').show();
                    $('#add__button').text('Закрыть');
                } else if ($('.create__container').is(':visible')) {
                    $('.create__container').hide();
                    $('#add__button').text('+Добавить');
                } else if ($('.update__container').is(':visible')) {
                    $('.update__container').hide();
                    $('#add__button').text('+Добавить');
                }
            });
            function verifyGroupName(form, nameField, originalNameField, event) {
                var newName = form.find(`input[name="${nameField}"]`).val();
                var originalName = form.find(`input[name="${originalNameField}"]`).val();

                if (newName === originalName) {
                    // Имя не изменилось, пропускаем проверку
                    return;
                }
                $.ajax({
                    url: '/Group/VerifyGroupName',
                    type: 'GET',
                    data: { createName: form.find(`input[name="${nameField}"]`).val() },
                    async: false,
                    success: function (result) {
                        if (!result) {
                            // Имя не уникально, предотвращаем отправку формы
                            event.preventDefault();
                            alert('Название группы должно быть уникальным.');
                        }
                    }
                });
            }
            $('form.create__form').submit(function (event) {
                verifyGroupName($(this), 'createName', null, event);
            });

            $('form.update__form').submit(function (event) {
                verifyGroupName($(this), 'updateName', 'originalName', event);
            });
        });
    </script>
}