University/Models/Student.cs
namespace University.Models
{
    public class Student
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Surname { get; set; } = string.Empty;
        public string? Patronymic { get; set; } = string.Empty;
        public DateTimeOffset DateOfBirth { get; set; } = DateTimeOffset.MinValue;
        public string? Description { get; set; } = string.Empty;
        public string ImagePath { get; set; } = "/images/default_empty.jpg";
        public Guid? GroupId { get; set; }
        public Group Group { get; set; }
    }
}

University/Models/StudentsViewModel.cs
namespace University.Models
{
    public class StudentsViewModel
    {
        public List<Student> Students { get; set; } = new List<Student>();
        public string SearchFIO { get; set; } = string.Empty;
        public string SearchGroup { get; set; } = string.Empty;
        public List<Student> FilteredStudents { get; set; } = new List<Student>();
        public List<Group> Groups { get; set; } = new List<Group>();
        public Student? SelectedStudent { get; set; }
    }
}

University/ViewModels/StudentsViewModel.cs
using University.Models;

namespace University.ViewModels
{
    public class StudentsViewModel
    {
        public List<Student> Students { get; set; } = new List<Student>();
        public string SearchFIO { get; set; } = string.Empty;
        public string SearchGroup { get; set; } = string.Empty;
        public List<Student> FilteredStudents { get; set; } = new List<Student>();
        public List<Group> Groups { get; set; } = new List<Group>();
        public Student? SelectedStudent { get; set; }
    }
}

University/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using University.Models;
using University.ViewModels;

namespace University.Controllers
{
    public class GroupController : Controller
    {
        private readonly ILogger<GroupController> _logger;

        ApplicationContext db;

        public GroupController(ILogger<GroupController> logger, ApplicationContext context)
        {
            _logger = logger;
            db = context;
        }

        public async Task<IActionResult> Groups(Guid? selectedCourse, string searchTerm)
        {
            var groups = await db.Groups.Include(g => g.Course).Include(g => g.Curator).ToListAsync();
            var courses = await db.Courses.ToListAsync();

            var uniqueNames = new HashSet<string>();
            var uniqueCourses = new List<Course>();

            foreach (var course in courses)
            {
                if (uniqueNames.Add(course.Name))
                {
                    uniqueCourses.Add(course);
                }
            }

            List<Group> filteredGroups = groups;
            Course selectedcourse = new Course();

            if (selectedCourse != null && selectedCourse != Guid.Empty)
            {
                filteredGroups = filteredGroups.Where(g => g.Course.Id == selectedCourse).ToList();
                selectedcourse = await db.Courses.FirstOrDefaultAsync(g => g.Id == selectedCourse);
            }

            if (!string.IsNullOrEmpty(searchTerm))
            {
                var searchTermcopy = searchTerm.ToLower();
                filteredGroups = filteredGroups.Where(g => g.Name.ToLower().Contains(searchTermcopy)).ToList();
            }

            var model = new GroupsViewModel
            {
                Groups = groups,
                UniqueCourses = uniqueCourses,
                SelectedCourse = selectedcourse,
                SearchTerm = searchTerm,
                FilteredGroups = filteredGroups,
                Teachers = await db.Teachers.ToListAsync()
            };

            ViewData["Title"] = "Groups List";
            return View("Groups", model);
        }
        [HttpGet]
        public async Task<IActionResult> SearchGroups(Guid? selectedCourse, string searchTerm)
        {
            return RedirectToAction("Groups", new { selectedCourse, searchTerm });
        }
        [HttpPost]
        public async Task<IActionResult> CreateGroup(string? createName, Guid createCourse, Guid createCurator, string createDesc = "")
        {
            Group newGroup = new Group
            {
                Name = createName,
                Description = createDesc,
                CourseId = (createCourse != null && createCourse != Guid.Empty ? createCourse : null),
                Course = (createCourse != null && createCourse != Guid.Empty ? await db.Courses.FindAsync(createCourse) : null),
                CuratorId = (createCurator != null && createCurator != Guid.Empty) ? createCurator : null,
                Curator = (createCurator != null && createCurator != Guid.Empty) ? await db.Teachers.FindAsync(createCurator) : null
            };
            await db.Groups.AddAsync(newGroup);
            await db.SaveChangesAsync();
            return RedirectToAction("Groups");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateGroup(Guid updateId, string? updateName, Guid updateCourse, Guid updateCurator, string updateDesc = "")
        {
            var group = await db.Groups.Include(g => g.Course).Include(g => g.Curator).FirstOrDefaultAsync(t => t.Id == updateId);
            if (group != null)
            {
                group.Name = updateName;
                group.Description = updateDesc;
                group.CourseId = (updateCourse != null && updateCourse != Guid.Empty) ? updateCourse : null;
                group.Course = (updateCourse != null && updateCourse != Guid.Empty ? await db.Courses.FindAsync(updateCourse) : null);

                if (updateCurator != null && updateCurator != Guid.Empty)
                {
                    group.CuratorId = updateCurator;
                    group.Curator = await db.Teachers.FindAsync(updateCurator);
                }
                db.Update(group);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Groups");
        }
        public async Task<IActionResult> DeleteGroup(Guid GroupID)
        {
            var group = await db.Groups.FindAsync(GroupID);
            if (group != null)
            {
                db.Groups.Remove(group);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Groups");
        }

        [HttpGet]
        public async Task<IActionResult> VerifyGroupNameAsync(string createName)
        {
            var isUnique = !await db.Groups.AnyAsync(t => t.Name == createName);
            return Json(isUnique);
        }
    }
}

University/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using University.Models;
using University.ViewModels;

namespace University.Controllers
{
    public class StudentController : Controller
    {
        private readonly ILogger<StudentController> _logger;

        ApplicationContext db;

        public StudentController(ILogger<StudentController> logger, ApplicationContext context)
        {
            _logger = logger;
            db = context;
        }

        public async Task<IActionResult> Students(string? searchFIO, string? searchGroup, string? selectedStudent)
        {
            var students = await db.Students.Include(g => g.Group).ToListAsync();
            List<Student> filteredStudents = students;

            if (!string.IsNullOrEmpty(searchFIO))
            {
                var searchFIOcopy = searchFIO.ToLower();
                filteredStudents = HomeController.SearchPeople(filteredStudents, searchFIOcopy);
            }
            if (!string.IsNullOrEmpty(searchGroup))
            {
                searchGroup = searchGroup.ToLower();
                filteredStudents = filteredStudents.Where(g => g.Group != null && g.Group.Name.ToLower().Contains(searchGroup)).ToList();
            }

            var model = new StudentsViewModel
            {
                Students = students,
                SearchFIO = searchFIO,
                SearchGroup = searchGroup,
                FilteredStudents = filteredStudents,
                SelectedStudent = students.Find(g => g.Name == selectedStudent),
                Groups = await db.Groups.Include(g => g.Course).Include(g => g.Curator).ToListAsync()
            };
            ViewData["Title"] = "Students List";
            return View("Students", model);
        }
        [HttpGet]
        public async Task<IActionResult> SearchStudents(string? searchFIO, string? searchGroup, string selectedStudent = null)
        {
            return RedirectToAction("Students", new { searchFIO, searchGroup, selectedStudent });
        }
        [HttpPost]
        public async Task<IActionResult> CreateStudent(string? createName, string? createSurname, string? createPatronymic, DateTime createDateOfBirth, string? createDesc, IFormFile createImage, Guid crSelectedGroup)
        {
            Guid newID = Guid.NewGuid();
            Group group = await db.Groups.FindAsync(crSelectedGroup);
            Student newStudent = new Student
            {
                Id = newID,
                Name = createName,
                Surname = createSurname,
                Patronymic = createPatronymic,
                DateOfBirth = new DateTimeOffset(DateTime.SpecifyKind(createDateOfBirth, DateTimeKind.Utc)),
                Description = createDesc
            };
            if (group != null) newStudent.Group = group;
            if (createImage != null && createImage.Length > 0)
            {
                string fileName = $"{newID}{Path.GetExtension(createImage.FileName)}";
                string filePath = Path.Combine("wwwroot/images/Profiles/Students", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await createImage.CopyToAsync(stream);
                }
                newStudent.ImagePath = $"/images/Profiles/Students/{fileName}";
            }


            await db.Students.AddAsync(newStudent);
            await db.SaveChangesAsync();
            return RedirectToAction("Students");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateStudent(Guid updateId, string? updateName, string? updateSurname, string? updatePatronymic, DateTime updateDateOfBirth, string? updateDesc, IFormFile currentImagePath, Guid selectedGroup)
        {
            Guid newID = Guid.NewGuid();
            Group group = await db.Groups.FindAsync(selectedGroup);
            var student = await db.Students.Include(g => g.Group).FirstOrDefaultAsync(t => t.Id == updateId);
            if (student != null)
            {
                student.Name = updateName;
                student.Surname = updateSurname;
                student.Patronymic = updatePatronymic;
                student.DateOfBirth= new DateTimeOffset(DateTime.SpecifyKind(updateDateOfBirth, DateTimeKind.Utc));
                student.Description = updateDesc;
            }
            if (group != null) {
                student.Group = group;
            }
            if (currentImagePath != null && currentImagePath.Length > 0 && student != null)
            {
                string fileName = $"{student.Id}{Path.GetExtension(currentImagePath.FileName)}";
                string filePath = Path.Combine("wwwroot/images/Profiles/Students", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await currentImagePath.CopyToAsync(stream);
                }
                student.ImagePath = $"/images/Profiles/Students/{fileName}";
            }

            if (student != null)
            {
                db.Students.Update(student);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Students");
        }
        public async Task<IActionResult> DeleteStudent(Guid StudentID)
        {
            var student = await db.Students.FindAsync(StudentID);
            if (student != null)
            {
                if (!string.IsNullOrEmpty(student.ImagePath))
                {
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", student.ImagePath.TrimStart('/'));

                    if (System.IO.File.Exists(filePath) && student.ImagePath.TrimStart('/') != "images/default_empty.jpg")
                    {
                        System.IO.File.Delete(filePath);
                    }
                }

                db.Students.Remove(student);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Students");
        }
    }
}

University/Views/Student/Students.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model University.ViewModels.StudentsViewModel

@{
    var user = await UserManager.GetUserAsync(User);
    var isAdmin = user != null ? await UserManager.IsInRoleAsync(user, "Admin") : false;
}

@if (Model.SelectedStudent != null)
{
        Student student = Model.SelectedStudent;
        <div class="profile">
        <div class="profile__container">
            <p class="profile__status">Информация о студенте</p>
            <div class="profile__picture">
                @{
                    string filePath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", student.ImagePath.TrimStart('/'));
                }
                @if (System.IO.File.Exists(@filePath))
                {
                    <img src="@student.ImagePath" alt="Фото профиля" class="profile__picture_image">
                }
                else
                {
                    <img src="/images/default_empty.jpg" alt="Фото профиля отсутствует" class="profile__picture_image">
                }
            </div>
            <div class="profile__name_container">
                <p class="profile__name">Имя: @student.Name</p>
            </div>
            <div class="profile__surname_container">
                <p class="profile__surname">Фамилия: @student.Surname</p>
            </div>
            <div class="profile__patronymic_container">
                <p class="profile__patronymic">Отчество: @student.Patronymic</p>
            </div>
            <div class="profile__dateofbirth_container">
                <p class="profile__dateofbirth">Дата рождения: @student.DateOfBirth.ToString("dd-MM-yyyy")</p>
            </div>
            <div class="profile__description_container">
                <p class="profile__description">Описание: @(!string.IsNullOrEmpty(student.Description) ? student.Description : "*Пусто*")</p>
            </div>
            <div class="profile__group_container">
                <p class="profile__group">Группа: @student.Group.Name</p>
            </div>
        </div>
    </div>
}
else
{
    <form class="filter__form" asp-action="SearchStudents" asp-controller="Student" method="get">
        <div>
            <label>ФИО: </label>
            <input type="text" name="searchFIO" placeholder="ФИО студента..." value="@Model.SearchFIO" />

            <label>Группа: </label>
            <input type="text" name="searchGroup" placeholder="Группа..." value="@Model.SearchGroup" />
            <input type="submit" value="Поиск" />
        </div>
    </form>

    <table>
        <caption>Студенты</caption>
        <thead>
        <td>ФИО</td>
        <td>Дата рождения</td>
        <td>Описание</td>
        <td>Группа</td>
        @if (isAdmin)
        {
            <td colspan="2">Действия</td>
        }
        </thead>
        @if (Model.FilteredStudents != null && Model.FilteredStudents.Any())
        {
            @foreach (var student in Model.FilteredStudents)
            {
                <tr>
                    <td><a target="_blank" asp-action="SearchStudents" asp-controller="Student" asp-route-selectedStudent="@student.Name">@(@student.Surname + " " + @student.Name + " " + @student.Patronymic)</a></td>
                    <td>@student.DateOfBirth.ToString("dd-MM-yyyy")</td>
                    <td class="table__col_description">@(!string.IsNullOrEmpty(@student.Description) ? @student.Description : "*Пусто*")</td>
                    @if (student.Group != null)
                    {
                        <td> <a asp-controller="Group" asp-action="SearchGroups" asp-route-searchTerm="@student.Group.Name"> @student.Group.Name </a></td>
                    }
                    else
                    {
                        <td>Пусто</td>
                    }
                    @if (isAdmin)
                    {
                        <td>
                            <button type="button" class="update__button"
                                    data-id="@student.Id"
                                    data-name="@student.Name"
                                    data-surname="@student.Surname"
                                    data-patronymic="@student.Patronymic"
                                    data-dateofbirth="@student.DateOfBirth.ToString("o")"
                                    data-description="@student.Description"
                                    data-group="@(student.Group != null ? @student.Group.Id : (Model.Groups.Count > 0 ? Model.Groups[0].Id : ""))">
                                Изменить
                            </button>
                        </td>
                        <td><a asp-action="DeleteStudent" asp-controller="Student" asp-route-StudentID="@student.Id">Удалить</a></td>
                    }
                </tr>
            }
        }
        else
        {
            <tfoot><td colspan="@(isAdmin?6:4)">Результатов нет</td></tfoot>
        }
    </table>
    @if (isAdmin)
    {
        <div class="add__button_container">
            <button type="button" id="add__button" class="add__button">+Добавить</button>
        </div>

        <div class="create__container" style="display: none;">
            <form class="create__form" asp-action="CreateStudent" asp-controller="Student" method="post" enctype="multipart/form-data">
                <p class="create__name">Имя: </p>
                <input name="createName" placeholder="Имя..." required>
                <p class="create__surname">Фамилия:</p>
                <input name="createSurname" placeholder="Фамилия..." required>
                <p class="create__patronymic">Отчество (если есть):</p>
                <input name="createPatronymic" placeholder="Отчество...">
                <p class="create__dateOfBirth">Дата рождения:</p>
                <input type="date" id="createDateOfBirth" name="createDateOfBirth" placeholder="Дата рождения..." required>
                <p class="create__description">Описание:</p>
                <input name="createDesc" placeholder="Описание...">
                <p class="create__photo">Фотография:</p>
                <input type="file" name="createImage" placeholder="Фото...">
                <p class="create__subjects">Группа:</p>
                @if (Model.Groups.Count != 0)
                {
                    <select name="crSelectedGroup" class="create__groups_container">
                        @foreach (var group in Model.Groups)
                        {
                            <option value="@group.Id">@group.Name</option>
                        }
                    </select>
                }
                else
                {
                    <button type="button" class="create__group" onclick="location.href='@Url.Action("Groups", "Home")'">Создать группу</button>
                }
                <input class="create__btn" type="submit" value="Добавить студента">
            </form>
        </div>

        <div class="update__container" style="display: none;">
            <form class="update__form" asp-action="UpdateStudent" asp-controller="Student" method="post" enctype="multipart/form-data">
                <input type="hidden" name="updateId" id="updateStudentId" />
                <p class="update__name">Имя: </p>
                <input name="updateName" placeholder="Имя..." required>
                <p class="update__surname">Фамилия:</p>
                <input name="updateSurname" placeholder="Фамилия..." required>
                <p class="update__patronymic">Отчество (если есть):</p>
                <input name="updatePatronymic" placeholder="Отчество...">
                <p class="update__dateOfBirth">Дата рождения:</p>
                <input type="date" id="updateDateOfBirth" name="updateDateOfBirth" placeholder="Дата рождения..." required>
                <p class="update__description">Описание:</p>
                <input name="updateDesc" placeholder="Описание...">
                <p class="update__photo">Фотография:</p>
                <input type="file" name="currentImagePath" placeholder="Фото...">
                <p class="update__subjects">Группа:</p>
                @if (Model.Groups.Count != 0)
                {
                    <select name="selectedGroup" class="create__groups_container">
                        @foreach (var group in Model.Groups)
                        {
                            <option value="@group.Id">@group.Name</option>
                        }
                    </select>
                }
                else
                {
                    <button type="button" class="create__group" onclick="location.href='@Url.Action("Groups", "Home")'">Создать группу</button>
                }
                <input class="update__btn" type="submit" value="Обновить информацию">
            </form>
        </div>
    }
}
@section Scripts{
    <script>
        $(document).ready(function () {
            $('.update__button').on('click', function () {
                var studentId = $(this).data('id');
                var studentName = $(this).data('name');
                var studentSurname = $(this).data('surname');
                var studentPatronymic = $(this).data('patronymic');
                var studentDateOfBirth = $(this).data('dateofbirth');
                var studentDescription = $(this).data('description');
                var studentGroup = $(this).data('group');

                $('#updateStudentId').val(studentId);
                $('input[name="updateName"]').val(studentName);
                $('input[name="updateSurname"]').val(studentSurname);
                $('input[name="updatePatronymic"]').val(studentPatronymic);
                $('input[name="updateDateOfBirth"]').val(new Date(studentDateOfBirth).toISOString().split('T')[0]);
                $('input[name="updateDesc"]').val(studentDescription);

                $('select[name="selectedGroup"]').val(studentGroup);

                $('#add__button').text('Закрыть');
                if (!$('.update__container').is(':visible')) {
                    $('.create__container').hide();
                    $('.update__container').show();
                }
            });
            $('#add__button').on('click', function () {
                if (!$('.create__container').is(':visible') && !$('.update__container').is(':visible')) {
                    $('.create__container').show();
                    $('#add__button').text('Закрыть');
                } else if ($('.create__container').is(':visible')) {
                    $('.create__container').hide();
                    $('#add__button').text('+Добавить');
                } else if ($('.update__container').is(':visible')) {
                    $('.update__container').hide();
                    $('#add__button').text('+Добавить');
                }
            });
        });

        function checkImageFile(file) {
            const allowedExtensions = /(\.jpg|\.jpeg|\.png)$/i;

            const extension = '.' + file.name.split('.').pop();

            if (!allowedExtensions.exec(extension)) {
                alert('Выбранный файл не является изображением. Выберите файл с расширением .jpg, .jpeg или .png.');
                return false;
            }
            return true;
        }

        document.querySelector('input[type="file"]').addEventListener('change', () => {
            const file = this.files[0];
            if (file && !checkImageFile(file)) {
                this.value = '';
            }
        });
    </script>
}