University/Models/Subject.cs
namespace University.Models
{
    public class Subject
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public ICollection<Teacher> Teachers { get; set; }
    }
}

University/Models/SubjectsViewModel.cs
namespace University.Models
{
    public class SubjectsViewModel
    {
        public List<Subject> Subjects { get; set; } = new List<Subject>();
        public string SearchSubject { get; set; } = string.Empty;
        public List<Subject> FilteredSubjects { get; set; } = new List<Subject>();
    }
}

University/ViewModels/SubjectsViewModel.cs
using University.Models;

namespace University.ViewModels
{
    public class SubjectsViewModel
    {
        public List<Subject> Subjects { get; set; } = new List<Subject>();
        public string SearchSubject { get; set; } = string.Empty;
        public List<Subject> FilteredSubjects { get; set; } = new List<Subject>();
    }
}

University/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using University.Models;
using University.ViewModels;

namespace University.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ILogger<SubjectController> _logger;

        ApplicationContext db;

        public SubjectController(ILogger<SubjectController> logger, ApplicationContext context)
        {
            _logger = logger;
            db = context;
        }

        public async Task<IActionResult> Subjects(string? searchSubject)
        {
            var subjects = await db.Subjects.ToListAsync();
            List<Subject> filteredSubjects = subjects;

            if (!string.IsNullOrEmpty(searchSubject))
            {
                var searchSubjectCopy = searchSubject.ToLower();
                filteredSubjects = filteredSubjects.Where(g => g.Name.ToLower().Contains(searchSubjectCopy)).ToList();
            }

            var model = new SubjectsViewModel
            {
                Subjects = subjects,
                SearchSubject = searchSubject,
                FilteredSubjects = filteredSubjects
            };
            ViewData["Title"] = "Subjects List";
            return View("Subjects", model);
        }
        [HttpGet]
        public async Task<IActionResult> SearchSubjects(string? searchSubject)
        {
            return RedirectToAction("Subjects", new { searchSubject });
        }
        [HttpPost]
        public async Task<IActionResult> CreateSubject(string? createName)
        {

            Subject newSubject = new Subject
            {
                Name = createName
            };
            await db.Subjects.AddAsync(newSubject);
            await db.SaveChangesAsync();
            return RedirectToAction("Subjects");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateSubject(Guid? subjectId, string? updateName)
        {
            var subject = await db.Subjects.FindAsync(subjectId);
            if (subject != null)
            {
                subject.Name = updateName;
                db.Subjects.Update(subject);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Subjects");
        }
        public async Task<IActionResult> DeleteSubject(Guid SubjectID)
        {
            var subject = await db.Subjects.FindAsync(SubjectID);
            if (subject != null)
            {
                db.Subjects.Remove(subject);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Subjects");
        }
        [HttpGet]
        public async Task<IActionResult> VerifySubjectName(string createName)
        {
            var isUnique = !await db.Subjects.AnyAsync(t => t.Name == createName);
            return Json(isUnique);
        }

    }
}

University/Views/Subject/Subjects.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model University.ViewModels.SubjectsViewModel

@{
    var user = await UserManager.GetUserAsync(User);
    var isAdmin = user != null ? await UserManager.IsInRoleAsync(user, "Admin") : false;
}

<form class="filter__form" asp-action="SearchSubjects" asp-controller="Subject" method="get">
    <div>
        <label>Название: </label>
        <input type="text" name="searchSubject" placeholder="Название предмета..." value="@Model.SearchSubject" />
        <input type="submit" value="Поиск" />
    </div>
</form>

<table>
    <caption>Предметы</caption>
    <thead>
        <td>Наименование</td>
        @if (isAdmin)
        {
            <td colspan="2">Действия</td>
        }
    </thead>
    @if (Model.FilteredSubjects != null && Model.FilteredSubjects.Any())
    {
        @foreach (var subject in Model.FilteredSubjects)
        {
            <tr>
                <td>@subject.Name</td>
                @if (isAdmin)
                {
                    <td><button type="button" class="update__button" data-id="@subject.Id" data-name="@subject.Name">Изменить</button></td>
                    <td><a asp-action="DeleteSubject" asp-controller="Subject" asp-route-SubjectID="@subject.Id">Удалить</a></td>
                }
            </tr>
        }
    }
    else
    {
        <tfoot><td colspan="@(isAdmin?3:1)">Результатов нет</td></tfoot>
    }
</table>

@if (isAdmin)
{
    <div class="add__button_container">
        <button type="button" id="add__button" class="add__button">+Добавить</button>
    </div>

    <div class="create__container" style="display: none;">
        <form class="create__form" asp-action="CreateSubject" asp-controller="Subject" method="post">
            <p class="create__name">Название: </p>
            <input name="createName" placeholder="Название..." required>
            <input class="create__btn" type="submit" value="Создать предмет">
        </form>
    </div>

    <div class="update__container" style="display: none;">
        <form class="update__form" asp-action="UpdateSubject" asp-controller="Subject" method="post">
            <input type="hidden" name="originalName" value="" id="originalName">
            <input type="hidden" name="subjectId" id="updateSubjectId" />
            <p class="create__name">Название: </p>
            <input name="updateName" id="updateSubjectName" placeholder="Название...">
            <input class="update__btn" type="submit" value="Обновить информацию">
        </form>
    </div>
}

@section Scripts{
    <script>
        $(document).ready(function () {
            $('.update__button').on('click', function() {
                var subjectId = $(this).data('id');
                var subjectName = $(this).data('name');
                console.log(subjectName);

                $('#updateSubjectId').val(subjectId);
                $('#updateSubjectName').val(subjectName);
                $('#originalName').val(subjectName);

                $('#add__button').text('Закрыть');
                if (!$('.update__container').is(':visible')) {
                    $('.create__container').hide();
                    $('.update__container').show();
                }
            });
            $('#add__button').on('click', function () {
                if (!$('.create__container').is(':visible') && !$('.update__container').is(':visible')) {
                    $('.create__container').show();
                    $('#add__button').text('Закрыть');
                } else if ($('.create__container').is(':visible')) {
                    $('.create__container').hide();
                    $('#add__button').text('+Добавить');
                } else if ($('.update__container').is(':visible')) {
                    $('.update__container').hide();
                    $('#add__button').text('+Добавить');
                }
            });
            function verifySubjectName(form, nameField, originalNameField, event) {
                var newName = form.find(`input[name="${nameField}"]`).val();
                var originalName = form.find(`input[name="${originalNameField}"]`).val();

                if (newName === originalName) {
                    // Имя не изменилось, пропускаем проверку
                    return;
                }
                $.ajax({
                    url: '/Subject/VerifySubjectName',
                    type: 'GET',
                    data: { createName: form.find(`input[name="${nameField}"]`).val() },
                    async: false,
                    success: function (result) {
                        if (!result) {
                            // Имя не уникально, предотвращаем отправку формы
                            event.preventDefault();
                            alert('Название предмета должно быть уникальным.');
                        }
                    }
                });
            }

            $('form.create__form').submit(function (event) {
                verifySubjectName($(this), 'createName', null, event);
            });

            $('form.update__form').submit(function (event) {
                verifySubjectName($(this), 'updateName', 'originalName', event);
            });
        });
    </script>
}